#!/bin/bash
usage() {
	echo "Usage:"
	echo "  ${0} <after|before> <packagename>"
	echo "    or"
	echo "  ${0} <after|before> <epochtime>"
	echo ""
	echo "Examples:"
	echo "  ${0} after glibc"
	echo "  ${0} before gcc-6"
	echo "  ${0} before 1512655201"
	echo ""
	echo "Note: package specifications rely on qlist -I matching"
	exit
}

if ! [[ $# == 2 ]]; then
	usage
fi


#parse $1
if [ ${1} == "after" ]; then
	operator="-gt"
elif [ ${1} == "before" ]; then
	operator="-lt"
else
	echo "arg1 must be 'before' or 'after'"
	echo ""
	usage
	exit
fi

#parse $2
if [[ "$2" =~ ^[0-9]+$ ]]; then
	timestamp=${2}
elif qlist -ICve ${2} &>/dev/null; then
	timestamp=$(cat /var/db/pkg/$(qlist -ICve ${2} | head -n1)/BUILD_TIME)
elif qlist -ICv ${2} &>/dev/null; then
	timestamp=$(cat /var/db/pkg/$(qlist -ICv ${2} | head -n1)/BUILD_TIME)
else
	echo "Don't know what to do with arg2"
	echo ""
	usage
	exit
fi

#echo operator: $operator
#echo timestamp: $timestamp

pushd /var/db/pkg > /dev/null || ( echo "Uh oh, can't read VDB" && exit )
for i in */*; do
	[ $(cat ${i}/BUILD_TIME) ${operator} ${timestamp} ] && echo ${i} | sed -e 's/^/=/'
done
popd >/dev/null
